const mockUsers = [
  {
    id: 1,
    name: "Uday Kalyan",
    email: "udaykalyan@gmail.com",
    avatar: "https://www.profilebakery.com/wp-content/uploads/2023/03/Profilbild-AI.jpg",
    lastSeen: "10:45 AM",
    messages: [
      {
        id: 21,
        text: "Are we still meeting tomorrow?",
        timestamp: "9:00 AM",
        status: "delivered",
        sentByUser: false,
        media: "https://jooinn.com/images/beautiful-lake-5.jpg"
      },
      {
        id: 22,
        text: "Yes, same time and place. Can’t wait!",
        timestamp: "9:30 AM",
        status: "sent",
        sentByUser: true,
      },
      {
        id: 23,
        text: "Perfect! Let me know if anything changes.",
        timestamp: "10:00 AM",
        status: "seen",
        sentByUser: false,
      },
      {
        id: 24,
        text: null,               //"Got it, see you then!",
        timestamp: "10:30 AM",
        status: "seen",
        sentByUser: true,
        media: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
      },
      {
        id: 25,
        text: "Looking forward to catching up!",
        timestamp: "11:00 AM",
        status: "delivered",
        sentByUser: false,
      },
    ],
  },
  {
    id: 2,
    name: "Anjali Sharma",
    email: "anjaliSharma@gmail.com",
    avatar: "https://img.freepik.com/premium-photo/headshot-photos-indian-women-dynamic-professions-occassions-indian-girl_978786-295.jpg?w=2000",
    lastSeen: "Yesterday",
    messages: [
      {
        id: 16,
        text: "Sounds great, thanks!",
        timestamp: "6:00 PM",
        status: "seen",
        sentByUser: true,
      },
      {
        id: 17,
        text: "No problem, happy to help!",
        timestamp: "6:30 PM",
        status: "seen",
        sentByUser: false,
      },
      {
        id: 18,
        text: "Did you finish the report?",
        timestamp: "7:00 PM",
        status: "delivered",
        sentByUser: false,
      },
      {
        id: 19,
        text: "Almost there! Just finalizing it now.",
        timestamp: "7:30 PM",
        status: "sent",
        sentByUser: true,
      },
      {
        id: 20,
        text: "Great, let me know once it’s done.",
        timestamp: "8:00 PM",
        status: "seen",
        sentByUser: false,
      },
    ],
  },
  {
    id: 3,
    name: "John Doe",
    email: "johnDoe@gmail.com",
    avatar: "https://img.freepik.com/premium-photo/happy-man-ai-generated-portrait-user-profile_1119669-1.jpg?w=2000",
    lastSeen: "2 hours ago",
    messages: [
      {
        id: 11,
        text: "Can you help me with the project timeline?",
        timestamp: "4:00 PM",
        status: "delivered",
        sentByUser: false,
      },
      {
        id: 12,
        text: "Sure! Send me the details, and I’ll review it.",
        timestamp: "4:15 PM",
        status: "sent",
        sentByUser: true,
      },
      {
        id: 13,
        text: "Done! Let me know what you think.",
        timestamp: "4:30 PM",
        status: "seen",
        sentByUser: false,
      },
      {
        id: 14,
        text: "Looking good so far. A few adjustments here and there.",
        timestamp: "5:00 PM",
        status: "seen",
        sentByUser: true,
      },
      {
        id: 15,
        text: "Got it! I’ll make the changes and send it back.",
        timestamp: "5:30 PM",
        status: "delivered",
        sentByUser: false,
      },
    ],
  },
  {
    id: 4,
    name: "Emma Watson",
    email: "emmawatson@gmail.com",
    avatar: "https://www.profilebakery.com/wp-content/uploads/2023/04/AI-Profile-Picture-400x400.jpg",
    lastSeen: "5 minutes ago",
    messages: [
      {
        id: 6,
        text: "What time should we meet tomorrow?",
        timestamp: "2:00 PM",
        status: "delivered",
        sentByUser: false,
      },
      {
        id: 7,
        text: "I can do 3 PM, is that good for you?",
        timestamp: "2:15 PM",
        status: "sent",
        sentByUser: true,
      },
      {
        id: 8,
        text: "Sure! See you at 3 PM.",
        timestamp: "2:30 PM",
        status: "seen",
        sentByUser: false,
      },
      {
        id: 9,
        text: "Looking forward to our presentation.",
        timestamp: "3:00 PM",
        status: "delivered",
        sentByUser: true,
      },
      {
        id: 10,
        text: "Me too! Let’s make it great.",
        timestamp: "3:30 PM",
        status: "seen",
        sentByUser: false,
      },
    ],
  },
  {
    id: 5,
    name: "Rahul Verma",
    email: "rahulverma@gmail.com",
    avatar: "https://www.profilebakery.com/wp-content/uploads/2023/04/PROFILE-PICTURE-FOR-FACEBOOK.jpg",
    lastSeen: "Online",
    messages: [
      {
        id: 1,
        text: "Hey, how's it going?",
        timestamp: "10:15 AM",
        status: "seen",
        sentByUser: true,  // True if the message is sent by the current user
      },
      {
        id: 2,
        text: "Almost done! Just a few tweaks left.",
        timestamp: "12:15 PM",
        status: "seen",
        sentByUser: false,  // False if the message is received
      },
      {
        id: 3,
        text: "Great! Let me know when you’re ready for a review.",
        timestamp: "12:45 PM",
        status: "seen",
        sentByUser: true,
      },
      {
        id: 4,
        text: "Will do, thanks!",
        timestamp: "1:00 PM",
        status: "seen",
        sentByUser: false,
      },
      {
        id: 5,
        text: "Perfect, talk soon!",
        timestamp: "1:30 PM",
        status: "seen",
        sentByUser: true,
      }
    ],
  },
];

export default mockUsers;
